### ISSUE TITLE
Example Report not knitting on master with default parameters

### ISSUE THREAD

**Issue by HorridTom** [HorridTom/hospitalflow#91]
When I knit example-report.Rmd on master I get the following error: 

`Quitting from lines 146-152 (example-report.Rmd) 
Error in data.frame(x, y, n, notes, facets, cl, target) : 
  arguments imply differing number of rows: 0, 1
Calls: <Anonymous> ... eval -> eval -> <Anonymous> -> <Anonymous> -> data.frame`

This seems to be happening in the call to `hospitalflow::four_hrs_perf_flow_groups` on [line 146](https://github.com/HorridTom/hospitalflow/blob/8c63e2101babf48ff0cbf5bfe8317d33876a4c42/vignettes/example-report.Rmd#L146)

**Comment by ImogenConnorHelleur** [comment]
The problem was that there were no flow 1s identified in the sample data used to run the report. I've fixed it now so that a blank plot is produced in the grid if any of the flows have no data. We can decide whether we want these to be blank or to say something like "no observations in the flow 1 group were identified".

**Comment by ImogenConnorHelleur** [comment]
Trying to fix issue with `agerage_ed_los_flows()` as well before I pull request. It's not cooperating at the moment so will revisit next week.
