### ISSUE TITLE
Set up tests to only use synthetic data

### ISSUE THREAD

**Issue by ImogenConnorHelleur** [HorridTom/hospitalflow#95]

**Comment by ImogenConnorHelleur** [comment]
I looks like most of the file in the testdata folder are real data (or could be real data). I think we could definitely just remove columns that we don't use for a lot of these tests.

It also looks like we have csv, rds and xlsx versions of some of the data. Would be good to work out which ones are actually used and delete any extras.

**Comment by ImogenConnorHelleur** [comment]
Hi @HorridTom ,

To keep it simple I've divided the test data in half for us to look at (I'll start in Monday). 

![image](https://user-images.githubusercontent.com/31736674/150830943-88f7509d-257a-4069-8ecd-339dd359f0f9.png)

I plan to use the synthetic folder in the `data` folder of the repo for more complicated test data that can't be perturbed easily.

**Comment by HorridTom** [comment]
Hi @ImogenConnorHelleur thanks for this. I have done three things on this today:
1) Changed the .gitignore file to ignore each of these subfolders of testdata _separately_, so that we can remove them from the gitignore file as we fix the data in each - so we can then commit that data ([82bbc00](https://github.com/HorridTom/hospitalflow/commit/82bbc00316a57abb83341687f7986d2fc45dcf8a))
2) Created a new branch [enhance-synth-testdata-95](https://github.com/HorridTom/hospitalflow/tree/enhance-synth-testdata-95) that we (or I, if you prefer to make your own branch - the only file we will collide on is .gitignore I think) can use to work on this issue
3) Fixed the first folder on my list - los_att_adm_tests ([36a6a44](https://github.com/HorridTom/hospitalflow/commit/36a6a44ecb0d5198649d5eb0b61d60f09380a74e)). In doing (3), I wrote a function to randomly perturb the spell start and end times so that the length of stay remains in the same 15min bin as the original (thus preserving the 'correct answer'). In case this is useful for any of yours, it is [here](https://gist.github.com/HorridTom/60511a2d1be95f5b9fbd69ebc995bd94).

**Comment by HorridTom** [comment]
I've done one more folder of test data today (los_distrib_method_admission, renamed from previous name). I won't keep on commenting here every time I do another one from now, as hopefully it is clear from the commits and the progress indicated by commenting out the individual folders in the .gitignore file...

**Comment by ImogenConnorHelleur** [comment]
![image](https://user-images.githubusercontent.com/31736674/152815041-08dbb003-c30b-456a-ba63-073c3a990bd4.png)

**Comment by ImogenConnorHelleur** [comment]
All test folders now checked and amended if needed. Haven't committed because I want to talk through the gitignore first.
